name: $(Version)$(Rev:.r)

pool:
  name: Hosted macOS
  demands: msbuild

#Your build pipeline references an undefined variable named ‘echo $BUILD_SOURCEBRANCH | grep -Eo "[^/]+\$"’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  BuildConfiguration: 'Release'

steps:
- bash: |
   BRANCH=$(echo $BUILD_SOURCEBRANCH | grep -Eo "[^/]+\$")
   VERSION=$BUILD_BUILDNUMBER
   
   if ! [ $BRANCH = master ]; then
       VERSION=$VERSION-$BRANCH
       echo "##vso[build.updatebuildnumber]$VERSION"
   fi;
   
   echo "##vso[task.setvariable variable=Version]$VERSION"
  displayName: 'Bash Script'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    vstsFeed: 'AMPAS-Dev'
  condition: not(endsWith(variables['Build.SourceBranch'], 'merge'))

- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    configuration: '$(BuildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: '*.nuspec'
    versioningScheme: byEnvVar
    versionEnvVar: VERSION

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: 'AMPAS-Dev'
  enabled: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'